-- CreateTable
CREATE TABLE `PASSWORD_RESET_TOKEN` (
    `TokenID` VARCHAR(36) NOT NULL,
    `AccountID` VARCHAR(36) NOT NULL,
    `ResetCode` VARCHAR(6) NOT NULL,
    `ExpiresAt` DATETIME(3) NOT NULL,
    `IsUsed` BOOLEAN NOT NULL DEFAULT false,
    `CreatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `PASSWORD_RESET_TOKEN_AccountID_idx`(`AccountID`),
    INDEX `PASSWORD_RESET_TOKEN_ResetCode_idx`(`ResetCode`),
    INDEX `PASSWORD_RESET_TOKEN_ExpiresAt_idx`(`ExpiresAt`),
    INDEX `PASSWORD_RESET_TOKEN_IsUsed_idx`(`IsUsed`),
    PRIMARY KEY (`TokenID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `PASSWORD_RESET_TOKEN` ADD CONSTRAINT `PASSWORD_RESET_TOKEN_AccountID_fkey` FOREIGN KEY (`AccountID`) REFERENCES `ACCOUNT`(`AccountID`) ON DELETE CASCADE ON UPDATE CASCADE;
